USE db_usls;

INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Accountancy, Banking and Finance');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Business, Consulting and Management');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Charity and Voluntary Work');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Creative Arts and Design');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Education');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Energy and Utilities');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Engineering and Manufacturing');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Environment and Agriculture');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Healthcare');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Hospitality and Events Management');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Information Research and Analysis');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Information Technology');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Insurance and Pensions');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Law');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Law Enforcement and Security');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Leisure, Sport and Tourism');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Marketing, Advertising and PR');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Media and Internet');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Performing Arts');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Property and Construction');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Public Service and Administration');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Publishing and Journalism');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Recruitment and HR');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Retail');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Sales');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Science and Pharmaceuticals');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Social Care');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Teaching and Education');
INSERT INTO `tbl_industry` (`industry_name`) VALUES ('Transport and Logistics');

INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Academic Librarian');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Accomodation Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Accounting Technician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Actor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Actuary');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Acupuncturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Adult Guidance Worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Adult Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Advertising Account Planner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Advertising Art Director');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Advertising Copywriter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Advice Worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Aerospace Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Agricultural Consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Air Cabin Crew');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Air Traffic Controller');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Airline Pilot');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Amenity Horticulturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Analytical Chemist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Animal Nutritionist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Animal Technician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Animator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Applications Developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Arboriculturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Archaelogist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Architect');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Architectural Technologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Archivist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Armed Forces Logistics/ Support Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Armed Forces Operational Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Armed Forces Technical Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Armed Forces Training and Education Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Arts Administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Automotive Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Barrister');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Barrister’s Clerk');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Broadcast Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Biomedical Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Biomedical Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Bookseller');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Broadcast Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Broadcast Presenter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building Control Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building Services Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10003','Charity Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Chartered Accountant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Chartered Certified Accountant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Air Cabin Crew');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10025','Call Centre Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television Camera Operator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Care Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Catering Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Careers Adviser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Careers Information Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Cartographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Ceramics Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10003','Charity Fundraiser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Chartered Loss Adjuster');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Chartered Public Finance Accountant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Civil Service Administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Civil Service Fast Streamer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Claims Handler');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Chartered management accountant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Analytical chemist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Child psychotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Podiatrist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Chiropractor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Consulting civil engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Clinical psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Clinical psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare scientist, clinical biochemistry');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare scientist, genetics');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Clinical embryologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Clinical research associate');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare scientist, histocompatibility and immunogenetics');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Clothing/textile technologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Colour technologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Commercial art gallery manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Commercial horticulturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Commercial/residential surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Commissioning editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Communications engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Community arts worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Community development worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Community education officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Community pharmacist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Company secretary');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Games developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Conference centre manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Historic buildings inspector/conservation officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Nature conservation officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Furniture conservator/restorer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/gallery conservator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Consulting civil engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Contracting civil engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Control and instrumentation engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Publishing copy-editor/proofreader');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Advertising copywriter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Corporate investment banker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Corporate treasurer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Counselling psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Counsellor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/gallery curator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10025','Customer service manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Information security specialist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dance movement psychotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Dancer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Information systems manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Database administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Financial trader');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dentist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Glass blower/designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Ceramics designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Exhibition designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Fashion designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Furniture designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Graphic designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Industrial/product designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Textile designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Community development worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10003','International aid/development worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Diagnostic radiographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dietitian');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Digital marketer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Diplomatic Services operational officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Dispensing optician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dramatherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Drilling engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Early years teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Ecologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Economist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Commissioning editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Magazine features editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Editorial assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Education administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Community education officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Environmental education officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum education officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Educational psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Chemical engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building services engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Broadcast engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Biomedical engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Automotive engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Land-based engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Aerospace engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Energy manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Emergency planning/management officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Clinical embryologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Consulting civil engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Contracting civil engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Communications engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Control and instrumentation engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Drilling engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Electrical engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Electronics engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Energy engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Maintenance engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','IT technical support officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing systems engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Materials engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Mining engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Petroleum engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Site engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Structural engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Technical sales engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Water engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Engineering geologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','English as a foreign language teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Environmental consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Environmental education officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Environmental health practitioner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Environmental manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Epidemiologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Equality and diversity officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Financial trader');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Ergonomist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Estate agent');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Rural practice surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Information security specialist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Event organiser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Personal assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Exercise physiologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Exhibition designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/gallery exhibitions officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Facilities manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Farm manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Fashion designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Fast food restaurant manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Geophysicist/field seismologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Field trials officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Film/video editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Financial adviser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Chartered management accountant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Financial manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Financial risk analyst');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Financial trader');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Fine artist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Firefighter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Fish farm manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Fisheries officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Fitness centre manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Food technologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Forensic psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Forensic scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Forest/woodland manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Freight forwarder');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Furniture conservator/restorer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Furniture designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Further education lecturer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Broadcast engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Games developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Clothing/textile technologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','General practice doctor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Geochemist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Geographical information systems officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Engineering geologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Wellsite geologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Geophysical data processor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Geophysicist/field seismologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Geoscientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Glass blower/designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Government social research officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Graphic designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Health and safety adviser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Health and safety inspector');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Radiation protection practitioner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Health promotion specialist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Health service manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Health visitor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Herbalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Heritage manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Higher education careers adviser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Historic buildings inspector/conservation officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Holiday representative');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Homeopath');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Horticultural consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Horticultural therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Amenity horticulturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Commercial horticulturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Hotel manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Housing manager/officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Human resources officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Hydrogeologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Hydrographic surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Hydrologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Illustrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Purchasing Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Industrial/Product Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Information Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Information Security Specialist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Information Systems Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Account Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Broker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Claims Handler');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Risk Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insuranace Underwriter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Intelligence Analyst');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Interior and Spatial Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Internal Auditor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10003','International Aid/Development Worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Interpreter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Investment Analyst');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Corporate Investment Banker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Operational Investment Banker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','IT Consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','IT Sales Professional');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','IT Technical Support Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','IT Trainer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Jewellery Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Broadcast Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Magazine Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Newspaper Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Land/Geomatics Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Landscape Architect');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Barrister');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Training and Development Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Learning Disability Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Learning Mentor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Further Education Lecturer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Higher Education Lecturer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Chartered Legal Executive');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Fitness Centre Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Lexicographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Public Librarian');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Licensed Conveyancer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Lighting Technician, Broadcasting/Film/Video');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Local Government Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Location Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Logistics and Distribution Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Chartered Loss Adjuster');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Magazine Features Editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Magazine Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Maintenance Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Management Consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Merchant Navy Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing Systems Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Market Researcher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Marketing Executive');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Materials Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Mechanical Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Media Buyer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Media Planner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Medical Illustrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Biomedical Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10025','Medical Sales Representative');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Mental Health Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Metallurgist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Meteorologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Microbiologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Midwife');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Minerals Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Mining Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Mudlogger');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Multimedia Programmer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Multimedia Specialist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum Education Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/Gallery Conservator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/Gallery Curator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Museum/Gallery Exhibitions Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Music Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Private Music Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Musician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Nurse Conservation Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Naval Architect');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Network Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Newspaper Journalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Adult Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Learning Disability Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Mental Health Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Nutritional Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Nutritionist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Occupational Hygienist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Oceanographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Office Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Operational Investment Banker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Operational Researcher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Wellsite Geologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Ophthalmologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Dispensing Optician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Optometrist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Orthoptist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Osteopath');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Outdoor Activities/Education Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Paediatric Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Paramedic');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Passenger - Transport Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Patent Attorney');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Patent Examiner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Personal Assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Human Resources Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Petroleum Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Community Pharmacist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Hospital Pharmacist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Pharmacologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Physiotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Herbalist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Airline Pilot');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Plant Breeder/Geneticist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Podatrist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Police Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Broadcast Presenter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Press Photographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Press Sub-editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Print Production Planner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Printmaker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Prison Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Private Music Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Radio Producer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television/Film/Video Producer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Industrial/Product Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Product/Process Development Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Radio Broadcast Assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television Production Coordinator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Production Designer, Theatre/Television/Film');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Manufacturing Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Production Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Programme Researcher, Broadcasting/Film/ Video');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Applications Developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Multimedia Programmer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Mental Health Nurse');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Hospital Doctor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Clinical Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Counselling Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Educational Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Occupational Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Sport and Exercise Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Psychotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Child Psychotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dance Movement Psychotherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Public Affairs Consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Public House Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Public Librarian');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Public Relations Account Executive');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Public Relations Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Publishing Copy-Editor/Proofreader');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Publishing Rights Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Purchasing Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Quality Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Quantity Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Quarry Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Equality and Diversity Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Radiation Protection Practitioner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Radio Broadcast Assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Radio Producer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Diagnostic Radiographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Therapeutic Radiographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Nature Conservation Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Records Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Recruitment Consultant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Recycling Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Regulatory Affairs Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Government Social Research Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Politician Assistant');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Restaurant Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10010','Fast Food Restaurant Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10001','Retail Banker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Retail Buyer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Retail Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Retail Merchandiser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Financial Risk Analyst');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10002','Risk Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Runner, Broadcasting/Film/Video');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Rural Practice Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10025','Sales Executive');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','IT Sales Professional');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10017','Sales Promotion Account Executive');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Science Writer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Scientific Laboratory Technician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Biomedical Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Audiology');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Clinical Biochemistry');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Genetics');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Haematology');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Histocompatibility and Immunogenetics');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Immunology');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scientist, Medical Physics');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Forensic Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Marine Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Healthcare Scietist, Physiology');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Product/Process Development Scietist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Research Scientist (Life Sciences)');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Research Scientist (Maths)');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Research Scientist (Medical)');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Research Scientist (Physical Sciences)');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Water Quality Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Secondary School Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Secretary/Administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Company Secretary');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Seismic Interpreter');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Senior Tax Professional/Tax Inspector');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Freight Forwarder');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Government Social Research Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Social Researcher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Social Worker');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Systems Developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Software Tester');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Soil Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10014','Solicitor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Sound Technician, Broadcasting/Film/Video');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Special Educational Needs Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Make-up Artist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Speech and Language Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Sport and Exercise Psychologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Sports Administrator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Sports Coach');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Sports Development Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Sports Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Statistician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Structural Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Press Sub-editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Hospital Doctor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Building Control Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Commercial/Residential Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Hydrographic Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10013','Insurance Risk Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Land/Geomatics Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Minerals Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Planning and Development Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Quantity Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Rural Practice Surveyor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Systems Analyst');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','System Developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Senior Tax Professional/Tax Inspector');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Further Education Lecturer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Early Years Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Private Music Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Primary School Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Secondary School Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','Special Education Needs Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Teaching Laboratory Technician');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Technical Author');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Technical Brewer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10007','Technical Sales Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10005','English as a Foreign Language Teacher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Telecommunication Researcher');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television Camera Operator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television Floor Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television Production Coordinator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Television/Film/Video Producer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10004','Textile Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Theatre Director');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10021','Theatre Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10019','Theatre Stage Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Theme Park Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Therapeutic Radiographer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Art Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Dramatherapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Horticultural Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Music Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Nutritional Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Occupational Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Speech and Language Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10009','Sports Therapist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Tour Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Tourism Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Tourist Information Centre Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10020','Town Planner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10026','Toxicologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Trade Mark Attorney');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Trade Union Research Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10015','Trading Standards Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10023','Training and Development Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10011','Translator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10028','Transport Planner');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10016','Travel Agency Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Arboriculturist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Veterinary Surgeon');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10018','Film/Video Editor');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Visual Merchandiser');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10003','Volunteer Coordinator');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Nature Conservation Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10024','Warehouse Manager');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Waste Management Officer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Water Engineer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10008','Water Quality Scientist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Web Designer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10012','Web Developer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10006','Wellsite Geologist');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10022','Writer');
INSERT INTO `tbl_profession` (`industry_id`,`profession_name`) VALUES ('10027','Youth Worker');